### ISSUE TITLE
Broken build with libcurl < 7.56

### ISSUE THREAD

**Issue by remicollet** [openswoole/swoole-src#102]
In thirdparty/php/curl/curl_private.h

```
#if LIBCURL_VERSION_NUM >= 0x073800 /* 7.56.0 */
	zval                          postfields;
#endif

```

So, when building with old curl, ex 7.29 in RHEL-7

```
/builddir/build/BUILD/php81-php-pecl-openswoole-4.9.0/NTS/thirdparty/php/curl/interface.cc:402:29: error: 'struct php_curl' has no member named 'postfields'
  402 |     postfields = &clone_ch->postfields;
      |                             ^~~~~~~~~~

```

**Comment by doubaokun** [comment]
Thanks.
